version: '3.8'

services:

  # PHP-FPM Service (Application logic)
  app:
    # Build the image using the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    # Mount the current directory as a volume for real-time code changes
    volumes:
      - .:/var/www/html
    # Environment variables for database connection (replace with actual values)
    environment:
      # These variables can be accessed in your PHP code via getenv()
      MYSQL_HOST: db
      MYSQL_DATABASE: dmonv_db
      MYSQL_USER: dmonv_user
      MYSQL_PASSWORD: secure_password
      # This assumes your PHP config file reads these environment variables.
    expose:
      - 9000 # Only expose FPM port to the Nginx service, not to the host machine

  # Nginx Service (Web Server)
  web:
    image: nginx:stable-alpine
    # Map host port 8080 to container port 80 for easy access (http://localhost:8080)
    ports:
      - "8080:80"
    volumes:
      # Mount the application code to serve static assets
      - .:/var/www/html
      # Mount the custom Nginx config file
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # Ensure Nginx starts after the PHP-FPM service
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:5.7
    # Use a persistent volume for the database data
    volumes:
      - db-data:/var/lib/mysql
    # Set the same environment variables as in the 'app' service for MySQL to initialize
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dmonv_db
      MYSQL_USER: dmonv_user
      MYSQL_PASSWORD: secure_password

# Volumes definition for data persistence
volumes:
  db-data:
